
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sxblog?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
server:
  port: 8090
mybatis-plus:
  mapper-locations: classpath:/mapper/sxblog/**.xml
  config-location: classpath:mybatis-config.xml
