
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://127.0.0.1:3306/sxblog?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false&serverTimezone=GMT%2B8
    username: root
<<<<<<< HEAD
    password: 12345678
  #邮件配置
  mail:
    host: smtp.163.com
    user: SXBlog_holiday@163.com
    ## 授权码
    password: AJFYYATCBRUUUZIJ
=======
    password: 156354
>>>>>>> f5e9943ec09e7d283d14bf160d01b4597a3e537c

server:
  port: 8090
mybatis-plus:
  mapper-locations: classpath:/mapper/sxblog/**.xml
  config-location: classpath:mybatis-config.xml


